In [ ]:
#--quiet fa un codice più breve perchè tutto attaccato

In [1]:
!pip install dtale --quiet

     |████████████████████████████████| 12.7 MB 5.3 MB/s
     |████████████████████████████████| 22.3 MB 1.6 MB/s
     |████████████████████████████████| 9.6 MB 32.8 MB/s
     |████████████████████████████████| 38.1 MB 1.2 MB/s
     |████████████████████████████████| 642 kB 51.9 MB/s
     |████████████████████████████████| 1.2 MB 43.9 MB/s
     |████████████████████████████████| 210 kB 65.7 MB/s
     |████████████████████████████████| 40 kB 4.8 MB/s
     |████████████████████████████████| 47 kB 4.0 MB/s
     |████████████████████████████████| 9.5 MB 50.6 MB/s
     |████████████████████████████████| 45 kB 3.1 MB/s
     |████████████████████████████████| 79.9 MB 101 kB/s
     |████████████████████████████████| 62 kB 910 kB/s
     |████████████████████████████████| 357 kB 51.1 MB/s
  Building wheel for dash-colorscales (setup.py) ... done
  Building wheel for dash-daq (setup.py) ... done
  Building wheel for ppscore (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.

In [2]:
import pandas as pd
import seaborn as sns
import dtale
import dtale.app as dtale_app

dtale_app.USE_COLAB = True

In [3]:
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'exercise', 'flights', 'fmri', 'gammas', 'geyser', 'iris', 'mpg', 'penguins', 'planets', 'taxis', 'tips', 'titanic']

In [ ]:
#seaborn come scikitlearn ha dentro un pò di dataset come librerie

In [4]:
df = sns.load_dataset('planets')
df

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [6]:
dtale.show(df)

https://rim6myws7vk-496ff2e9c6d22116-40000-colab.googleusercontent.com/dtale/main/1

In [ ]:
#questo è il nostro dtale

da dtale abbiamo fatto delle modifiche, poi abbiamo copiato il CODICE ed incollato sul colab. In automatico dtale ci inserisce anche 
il codice dell'ITERATIVE IMPUTER che ci converte in automatico i valori nulli con i VALORI PIù PROBABILI

In [9]:
# DISCLAIMER: 'df' refers to the data you passed in when calling 'dtale.show'

import pandas as pd

if isinstance(df, (pd.DatetimeIndex, pd.MultiIndex)):
	df = df.to_frame(index=False)

# remove any pre-existing indices for ease of use in the D-Tale code, but this is not required
df = df.reset_index().drop('index', axis=1, errors='ignore')
df.columns = [str(c) for c in df.columns]  # update columns to strings in case they are numbers

df.loc[:, 'year'] = pd.Series(df['year'].astype('str'), name='year', index=df['year'].index)
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

output = IterativeImputer().fit_transform(df[['orbital_period']])
df.loc[:, 'orbital_period'] = pd.DataFrame(output, columns=['orbital_period'], index=df.index)['orbital_period']